apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
type: Opaque
data:
  # Base64 encoded APP_KEY
  APP_KEY: "YmFzZTY0OkFja2ZTRUNYSXZuSzVyMjhHVklXVUF4bWJCc2pUc21GZjJ5MXBFWmNnL2M9Cg=="
  
  DB_PASSWORD: "U3VwZXJTZWNyZXRQYXNzd29yZDEyMyEK"