apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-worker
spec:
  replicas: 2
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: heavy-task-pool
      containers:
      - name: application
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"