apiVersion: v1
kind: ServiceAccount
metadata:
  name: laravel-k8s-sa
  namespace: production
  annotations:
    # Links the K8s SA to your GCP Service Account
    iam.gke.io/gcp-service-account: "laravel-app-sa@project-501674b6-7d67-40dc-99c.iam.gserviceaccount.com"