apiVersion: v1
kind: ServiceAccount
metadata:
  name: laravel-k8s-sa
  namespace: production
  annotations:
    # Links the K8s SA to your GCP Service Account
    iam.gke.io/gcp-service-account: "laravel-app-sa@project-4d486229-502c-4ea7-890.iam.gserviceaccount.com"