name: Deploy User Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: project-501674b6-7d67-40dc-99c
  GAR_LOCATION: asia-southeast1
  GAR_REPO: laravel-microservices-repo
  IMAGE_NAME: user-service
  CLUSTER_NAME: poc-gke-cluster
  CLUSTER_ZONE: asia-southeast1
  NAMESPACE: production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3
        ports:
          - 5672:5672

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          tools: composer:v2

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Prepare Environment
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan passport:keys
          sed -i 's/APP_URL=.*/APP_URL=http:\/\/localhost/' .env

      - name: Execute Tests (Pest)
        run: |
          vendor/bin/pest

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/1094681141696/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions-sa@project-501674b6-7d67-40dc-99c.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate Docker to GAR
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_ZONE }}

      - name: Set up Kustomize
        run: |-
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Deploy to GKE
        run: |
          cd k8s/apps/user-service/

          # Ensure the namespace exists before deploying
          kubectl get namespace ${{ env.NAMESPACE }} || kubectl create namespace ${{ env.NAMESPACE }}

          # Dynamically swap image tag
          kustomize edit set image base-image:placeholder=${{ env.IMAGE_TAG }}

          # Delete old migration job
          kubectl delete job -l component=migration --ignore-not-found -n ${{ env.NAMESPACE }}

          # Apply to GKE
          kustomize build . | kubectl apply -n ${{ env.NAMESPACE }} -f -

          # Wait for migration and rollout
          kubectl wait --for=condition=complete job/user-service-migrate --timeout=120s -n ${{ env.NAMESPACE }}
          kubectl rollout status deployment/user-service-laravel-app -n ${{ env.NAMESPACE }}
